[options]
admin_passwd = Restepo2!
db_host = db
db_port = 5432
db_user = odoo
db_password = Restepo2!
data_dir = /var/lib/odoo
proxy_mode = True
http_interface = 0.0.0.0
http_port = 8069
workers = 0
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200